- src/sidekick/index.md
In the future, the bookmarklet generator page should be updated from here vs in helix-pages, so changes that affect both the sidekick and this page can be released together.
> chore: add bookmarklet generator source

- .circleci/config.yml
- .releaserc.js
- package.json
> chore: enable semantic release

- src/sidekick/app.js
- test/app.test.js
> feat: fetch status initially, update preview, emit events

- src/sidekick/app.js
> fix: return the sidekick

- CHANGELOG.md
- package.json
- src/sidekick/app.js
- test/app.test.js
- test/fixtures/config-hlx3.html
> feat: use branch in outer cdn host if hlx3

- src/sidekick/app.js
Fix #32 
Test with https://sidekick-issue-32--helix-pages--adobe.hlx.page/tools/sidekick/
> fix: cors error while loading config.js

- src/sidekick/app.js
- test/app.test.js
> feat: detect outer cdn with and without ref

- src/sidekick/app.js
> fix: loading config.js fails on byocdn prod host

- src/sidekick/index.md
- allow hlx3 flag to be passed via URL
- show help text when helix logo is clicked
- only show from link if it has a value
> Bookmarklet generator enhancements

- docs/API.md
- src/sidekick/app.js
- src/sidekick/config.md
- test/app.test.js
> feat: add outerHost config property

- src/sidekick/fr.css
> feat: fr translations

- src/sidekick/app.js
- src/sidekick/config.md
- src/sidekick/de.css
- src/sidekick/fr.css
- test/app.test.js
- test/fixtures/config-hlx3-no-host.html
- test/fixtures/preview-onedrive-hlx3.html
Fix #51 
Fix #53 
Fix #58 
- update docs
- update i18n
> Sidekick updates

- src/sidekick/app.js
- test/app.test.js
> fix: leave prod hostnames with dashes alone

- src/sidekick/app.js
- test/app.test.js
- test/fixtures/config-hlx3-no-host.html
Fix #65 
You can test the fix with a sidekick from: https://sidekick-issue-65--helix-pages--adobe.hlx.page/tools/sidekick/?giturl=https://github.com/adobe/business-website
> fix: broken live button on hlx3 without prod host

- src/sidekick/app.js
- test/app.test.js
> fix: publish not working in hlx3 without host

- src/sidekick/app.css
- src/sidekick/app.js
- src/sidekick/de.css
- src/sidekick/fr.css
- test/app.test.js
> feat: load plugins on statusfetched

- test/app.test.js
- test/edit.test.js
- test/fixtures/is-preview.html
- test/live.test.js
- test/preview.test.js
- test/prod.test.js
- test/publish.test.js
- test/reload.test.js
- test/utils.js
For better maintainability, tests should be split per plugin.
> Split tests

- src/sidekick/index.md
> feat: switch to hlx3 config by default

- package-lock.json
- src/sidekick/app.js
- test/delete.test.js
- test/fixtures/reload-staging-code-hlx3.html
- test/reload.test.js
- test/utils.js
> feat: support code api

- src/sidekick/app.css
- src/sidekick/app.js
- test/app.test.js
- test/utils.js
> feat: use custom element for improved isolation

- src/sidekick/app.js
> fix: toggle error

- src/sidekick/app.js
> fix: devMode to use http://localhost:3000

- src/extension/manifest.json
- src/extension/utils.js
> fix: work with custom outerHost and any ref

- src/extension/manifest.json
- src/extension/utils.js
> fix(extension): handle errors fetching mountpoints

- src/extension/manifest.json
- src/extension/options.js
- src/extension/utils.js
> fix(extension): issues with options page

- src/extension/background.js
- src/extension/content.js
- src/extension/manifest.json
- src/extension/sidekick.js
- src/extension/utils.js
> feat: auto-pick project in local dev

- src/sidekick/module.js
> feat: use status API

- src/extension/background.js
> chore: reset proxy url every time

- src/extension/manifest.json
- src/extension/utils.js
> fix(extension): check for empty mountpoints

- src/sidekick/module.js
- test/preview.test.js
> fix: don't append editor search params

- src/sidekick/module.js
- test/preview.test.js
- test/utils.js
> feat: switch to new admin host

- src/sidekick/module.js
- test/app.test.js
- test/fixtures/preview-onedrive.html
- test/fixtures/pushdown-custom.html
> feat: adjust height of office online frame

- src/sidekick/module.js
> chore: remove whitespace from delete alert

- src/sidekick/app.css
- src/sidekick/module.js
> feat: show unpublished and source doc changes

- src/sidekick/module.js
- test/delete.test.js
> fix: no delete if no preview

- src/extension/_locales/de/messages.json
- src/extension/_locales/en/messages.json
- src/extension/manifest.json
- src/extension/options.html
- src/extension/options.js
> feat(extension): import/export config

- src/extension/manifest.json
- src/extension/utils.js
> fix(extension): project config not applied

- src/extension/content.js
- src/extension/manifest.json
- src/extension/utils.js
> fix(extension): more reasonable rendering rules

- src/extension/manifest.json
- src/extension/options.js
- src/extension/utils.js
> fix(extension): deal with mountpoint objects

- src/extension/configpicker.js
- src/extension/manifest.json
> fix(extension): config picker pushes down gdocs

- src/sidekick/app.css
- src/sidekick/de.css
- src/sidekick/fr.css
- src/sidekick/module.js
> feat: use less space on small screens

- .eslintignore
- build/build.js
- package-lock.json
- package.json
- src/extension/manifest.json
> feat(extension): build tooling for different browsers

- src/extension/manifest.json
- src/extension/options.html
> fix(extension): import broken

- src/extension/manifest.json
- src/extension/utils.js
> fix(extension): sidekick not showing on new docs

- .github/workflows/branch-release.yaml
- .github/workflows/release.yaml
- src/sidekick/app.css
- src/sidekick/de.css
- src/sidekick/fr.css
- src/sidekick/module.js
- src/sidekick/view/json.js
- test/app.test.js
Fix #193 
Features:
- user-friendly view on JSON data
- intelligent data represention for links, images, lists
- default table styling
- ability to register special views based on path (globbings)in config.js:
```js
specialViews: [
{
path: '/en/**.json',
js: (container, content) => {
const { limit, total } = JSON.parse(content);
container.textContent = `Custom data view - Showing ${limit} of ${total} records`;
},
css: '.hlx-sk-special-view { color: orange }',
},
],
```
Example:
> feat: special view for json

- src/sidekick/module.js
> fix: js error in checkLastModified

- src/sidekick/app.css
- src/sidekick/module.js
- src/sidekick/view/json.js
- test/app.test.js
- test/fixtures/custom-json-view.css
Changes:
- make sure last row(s) stays visible
- try to detect and format dates
- distinguish text from numbers
- use more natural word breaking
- allow relative path for custom css
- hide original content to avpid duplicate so user search results
> feat: json view enhancements

- src/sidekick/app.css
- src/sidekick/view/json.js
> feat: support multi-sheet in json view

- src/sidekick/module.js
- test/preview.test.js
> feat: special handling for /.helix/config.json

- src/sidekick/module.js
- test/app.test.js
- test/publish.test.js
> feat: support custom admin version

- src/sidekick/app.js
- test/app.test.js
> feat: load config from outer cdn

- src/sidekick/app.css
- src/sidekick/module.js
- test/app.test.js
- test/utils.js
> feat: dropdowns for plugins

- src/sidekick/module.js
- test/app.test.js
- test/edit.test.js
- test/live.test.js
- test/prod.test.js
- test/publish.test.js
- test/reload.test.js
- test/utils.js
Fix #38 
Fix #270 
- added `isEnabled` to `pluginButton` config
- sidekick now adding plugins on `contextloaded` instead of `statusfetched`
- plugins will re-evaluate themselves on `statusfetched`
> feat: add isEnabled to pluginButton

- README.md
- src/sidekick/module.js
- test/app.test.js
- test/delete.test.js
- test/edit.test.js
- test/preview.test.js
- test/reload.test.js
- test/utils.js
> feat: default to *.hlx.page

- src/sidekick/app.css
- src/sidekick/de.css
- src/sidekick/fr.css
- src/sidekick/module.js
> feat: improve help UX

- src/sidekick/module.js
> fix: prevent preview update if webPath undefined

- src/sidekick/app.css
- src/sidekick/de.css
- src/sidekick/fr.css
- src/sidekick/module.js
- test/app.test.js
- test/dev.test.js
> feat: advanced mode

- src/sidekick/app.css
- src/sidekick/module.js
- test/preview.test.js
- test/publish.test.js
> feat: show update indicator on preview button

- src/sidekick/app.css
- src/sidekick/de.css
- src/sidekick/fr.css
> chore: clarify sign in text

- src/sidekick/app.js
- src/sidekick/module.js
> chore: no strict mode in modules

- src/sidekick/fr.css
@rofe: I owe you those ;)
I did not translate the 4xx and 5xx error messages, they would be helpful neither to the end-user nor to the dev receiving a screenshot with the msg in french (apart maybe me...).
> chore: fr translations

- src/sidekick/module.js
- test/app.test.js
> fix: support custom sharepoint domain

- src/sidekick/module.js
> feat: pdf support

- src/sidekick/module.js
- test/preview.test.js
- test/utils.js
> fix: edit-preview fails on renamed documents

- src/sidekick/app.css
- src/sidekick/de.css
- src/sidekick/fr.css
- src/sidekick/module.js
- test/preview.test.js
Tell gdrive users to use google-native file formats
https://github.com/adobe/helix-sidekick-extension/issues/129
> Issue-129 - Tell gdrive users to use google-native file formats
